trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - bash: |
      git remote add secondary https://$TCX_GITHUB_TOKEN@github.com/dhruvit-r/AKImageCropperView.git
      git push secondary HEAD:refs/heads/develop --force --q
    env:
      TCX_GITHUB_TOKEN: $(TCX_GITHUB_TOKEN)
    displayName: 'Push To GitHub'
